# Generated by Django 3.0 on 2019-12-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newslettercipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLettercipients',
        ),
    ]
